version: '3.8'
services:
  accumulator:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./data:/usr/src/pyaccumulator/data
    user: accumuser
