[settings]
LOG_LEVEL = "INFO"
LOG_PATH = "/tmp/accumulator.log"
DATASERVER_REQ_TYPE = "map-netcdf"
DATASERVER_DATASET = "edu.ou.mesonet.standard"
DATASERVER_TIMEOUT = 10
CHILL_HOURS_VAR = "chill_hours"
MODELS_TO_RUN = ["chill_hours"]

[[settings.STATION_PARAMETERS]]
id = "stid"

[[settings.STATION_PARAMETERS]]
id = "tair"
units = "fahr"

[[settings.STATION_PARAMETERS]]
id = "relh"
units = "percent"